# Generated by Django 4.2.7 on 2023-11-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oggetto', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=100)),
                ('misura', models.CharField(max_length=5)),
                ('quantità', models.IntegerField(max_length=4)),
            ],
            options={
                'verbose_name': 'componente',
                'verbose_name_plural': 'componenti',
            },
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_int', models.CharField(max_length=20)),
                ('descrizione_intervento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lavorogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lavoro', models.DateField(auto_now=True)),
                ('contenuto', models.CharField(max_length=100)),
                ('orelavoro', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Mese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField(max_length=4)),
                ('mese', models.CharField(max_length=9)),
                ('fotobusta', models.ImageField(upload_to='')),
                ('pagabusta', models.IntegerField(max_length=7)),
                ('oremese', models.IntegerField(max_length=3)),
                ('differenza_ore', models.IntegerField(max_length=3)),
            ],
            options={
                'verbose_name': 'mese',
                'verbose_name_plural': 'mesi',
            },
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definizione', models.CharField(max_length=20)),
                ('immagine', models.ImageField(upload_to='')),
                ('superficie', models.IntegerField(max_length=6)),
                ('dettagli', models.CharField(max_length=100)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='villa_md.componente')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='villa_md.tipologia')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zone',
            },
        ),
        migrations.CreateModel(
            name='Azione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_azione', models.CharField(max_length=20)),
                ('descrizione_azione', models.CharField(max_length=200)),
                ('tempo_azione', models.IntegerField(max_length=3)),
                ('intervento_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavorogiorni', to='villa_md.intervento')),
                ('lavoro_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Azioni', to='villa_md.lavorogg')),
            ],
        ),
    ]
