# Generated by Django 4.2.7 on 2023-11-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azione',
            name='tempo_azione',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='componente',
            name='quantità',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lavorogg',
            name='orelavoro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mese',
            name='anno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mese',
            name='differenza_ore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mese',
            name='oremese',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mese',
            name='pagabusta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zona',
            name='superficie',
            field=models.IntegerField(),
        ),
    ]
