# Generated by Django 4.2.7 on 2023-11-25 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0002_alter_azione_tempo_azione_alter_componente_quantità_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lavorogg',
            new_name='GgLavoro',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='tipologia',
        ),
        migrations.AlterField(
            model_name='azione',
            name='intervento_appartenenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Azioni', to='villa_md.intervento'),
        ),
        migrations.DeleteModel(
            name='Componente',
        ),
        migrations.DeleteModel(
            name='Tipologia',
        ),
        migrations.DeleteModel(
            name='Zona',
        ),
    ]
