# Generated by Django 4.2.7 on 2023-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0003_rename_lavorogg_gglavoro_remove_zona_componente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GgLavoro',
            new_name='Orario',
        ),
        migrations.AddField(
            model_name='mese',
            name='saldato',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mese',
            name='fotobusta',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mese',
            name='oremese',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mese',
            name='pagabusta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
