# Generated by Django 4.2.7 on 2023-11-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0004_rename_gglavoro_orario_mese_saldato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mese',
            options={'verbose_name': 'Mese', 'verbose_name_plural': 'Mesi'},
        ),
    ]
