# Generated by Django 4.2.7 on 2023-11-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0005_alter_mese_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azione',
            options={'verbose_name': 'Azione', 'verbose_name_plural': 'Azioni'},
        ),
    ]
