# Generated by Django 4.2.7 on 2023-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0006_alter_azione_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervento',
            options={'verbose_name': 'Intervento', 'verbose_name_plural': 'Interventi'},
        ),
        migrations.AlterModelOptions(
            name='orario',
            options={'verbose_name': 'Orario', 'verbose_name_plural': 'Orari'},
        ),
        migrations.RenameField(
            model_name='orario',
            old_name='orelavoro',
            new_name='ore',
        ),
        migrations.RemoveField(
            model_name='orario',
            name='contenuto',
        ),
        migrations.RemoveField(
            model_name='orario',
            name='data_lavoro',
        ),
        migrations.AddField(
            model_name='orario',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
