# Generated by Django 4.2.7 on 2023-11-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0007_alter_intervento_options_alter_orario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orario',
            name='mese_appartenenza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orari', to='villa_md.mese'),
        ),
    ]
