# Generated by Django 4.2.7 on 2023-11-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa_md', '0008_orario_mese_appartenenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mese',
            name='saldato',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='orario',
            name='data',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
